development:
  adapter: postgresql
  encoding: unicode
  database: rails-demo_development
  host: localhost
  pool: 5
  username: jameslieu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails-demo_test
  host: localhost
  pool: 5
  username: jameslieu
  password:
